version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes: 
      - ./data/bdd:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD : password
      MYSQL_DATABASE : blog
      MYSQL_USER: user
      MYSQL_PASSWORD : password
    ports: 
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    restart: always
    ports:
      - 8081:80
